### ISSUE TITLE
arguments of toObject?

### ISSUE THREAD

**Issue by Jxck** [tc39/proposal-object-iteration#3]
```
  .toObject(([key]) => key, ([, value]) => value);
```

what is the first arg of second func ?

```
([???, value]) => value);
```

**Comment by ljharb** [comment]
they'd both be `[key, value]`.

**Comment by Jxck** [comment]
you mean like this ?

```
.toObject(
  ([key, value]) => key, // process for key
  ([key, value]) => value // process for value
)
```

then why separated ?

**Comment by decompil3d** [comment]
@Jxck The idea is that those functions are "selectors" for the key and value. In this contrived example, I'm operating on an entries-style array of key-value-pairs. But you could imagine working with an iterator on a collection of items that are not key-value-pairs, in which case you may want to select different things for key vs. value.

It's worth noting that `toObject` here might not truly be needed, since we already have `Object.fromEntries`. In the October meeting, folks expressed interest in having better left-to-right readability -- going from object -> iterator -> map -> back to object. For example:

```js
// These are functionally equivalent, but the 2nd one is easier to read left-to-right
Object.fromEntries(Iterator.from(obj).map(([k, v]) => [tx(k), tx(v)]));
Iterator.from(obj).map(([k, v]) => [tx(k), tx(v)]).toObject();
```

That 2nd line assumes that the key/value selector arguments are optional and default to entries-style items.

**Comment by Jxck** [comment]
@decompil3d what is the difference from below ?

```js
Object.fromEntries(Object.entries(o).map(fn))
```

**Comment by decompil3d** [comment]
`Object.entries` returns an array, not an iterator. So it makes a copy of the object entries rather than iterating over them in place.

**Comment by Jxck** [comment]
I see, thanks.
