### ISSUE TITLE
Clarification: What is the slippery slope?

### ISSUE THREAD

**Issue by andyfleming** [tc39/proposal-object-iteration#5]
> There was general support for improving the experience and optimizability of mapping over Objects, but folks were concerned about the slippery slope that adding a map method would create.

I believe it was discussed that this could lead to advocating for various array methods being provided for objects. Is that the extent of the concern? What would the specific downsides of that advocating or even acceptance and addition of those methods be?

**Comment by decompil3d** [comment]
Paraphrasing from the October 2019 meeting, I think that folks in the committee were concerned about bloating the `Object` global with additional collection methods like `reduce`, `filter`, `some`, `every`. Since these cannot be prototypal methods as we do with other collection types like `Map`, `Set`, `Array`, etc., they'd be strange, object-specific methods and overall bloat the language.

In the presence of the [Iterator Helpers](https://github.com/tc39/proposal-iterator-helpers) proposal, we could get practically _all_ of these commonly-used collection methods easily by just getting an iterator on the object. And those methods would be consistent across collection types.
